import type { Agent } from "@/types/agent"

export const agentsData: Agent[] = [
  {
    id: "agent-001",
    name: "Meeting Assistant Pro",
    type: "transcription",
    status: "active",
    usage: 98,
    rating: 4.9,
    totalSessions: 1247,
    lastUsed: "2024-01-15T10:30:00Z",
    createdAt: "2023-06-15T08:00:00Z",
    description: "Advanced AI transcription with real-time processing and speaker identification",
    features: ["Real-time transcription", "Speaker identification", "Keyword highlighting", "Export options"],
  },
  {
    id: "agent-002",
    name: "Smart Scheduler",
    type: "scheduling",
    status: "active",
    usage: 87,
    rating: 4.8,
    totalSessions: 892,
    lastUsed: "2024-01-15T09:15:00Z",
    createdAt: "2023-08-20T12:00:00Z",
    description: "Intelligent meeting scheduling with calendar integration and conflict resolution",
    features: ["Calendar sync", "Conflict detection", "Time zone handling", "Automated invites"],
  },
  {
    id: "agent-003",
    name: "Language Translator",
    type: "translation",
    status: "active",
    usage: 76,
    rating: 4.7,
    totalSessions: 634,
    lastUsed: "2024-01-14T16:45:00Z",
    createdAt: "2023-09-10T14:30:00Z",
    description: "Real-time language translation supporting 50+ languages",
    features: ["50+ languages", "Real-time translation", "Cultural context", "Accent adaptation"],
  },
  {
    id: "agent-004",
    name: "Analytics Engine",
    type: "analytics",
    status: "active",
    usage: 65,
    rating: 4.6,
    totalSessions: 445,
    lastUsed: "2024-01-15T08:20:00Z",
    createdAt: "2023-10-05T10:15:00Z",
    description: "Comprehensive meeting analytics and performance insights",
    features: ["Engagement metrics", "Speaking time analysis", "Sentiment tracking", "Custom reports"],
  },
  {
    id: "agent-005",
    name: "Content Moderator",
    type: "moderation",
    status: "inactive",
    usage: 23,
    rating: 4.2,
    totalSessions: 156,
    lastUsed: "2024-01-10T14:30:00Z",
    createdAt: "2023-11-12T16:45:00Z",
    description: "AI-powered content moderation for safe and professional meetings",
    features: [
      "Content filtering",
      "Inappropriate language detection",
      "Screen sharing monitoring",
      "Compliance reporting",
    ],
  },
  {
    id: "agent-006",
    name: "Voice Enhancement",
    type: "transcription",
    status: "maintenance",
    usage: 91,
    rating: 4.8,
    totalSessions: 723,
    lastUsed: "2024-01-12T11:20:00Z",
    createdAt: "2023-07-28T09:30:00Z",
    description: "Advanced voice processing with noise cancellation and clarity enhancement",
    features: ["Noise cancellation", "Voice clarity", "Echo reduction", "Audio optimization"],
  },
  {
    id: "agent-007",
    name: "Meeting Summarizer",
    type: "analytics",
    status: "active",
    usage: 82,
    rating: 4.7,
    totalSessions: 567,
    lastUsed: "2024-01-15T07:45:00Z",
    createdAt: "2023-08-15T13:20:00Z",
    description: "Intelligent meeting summarization with action items and key points extraction",
    features: ["Auto-summarization", "Action items", "Key points", "Follow-up reminders"],
  },
  {
    id: "agent-008",
    name: "Global Scheduler Pro",
    type: "scheduling",
    status: "active",
    usage: 94,
    rating: 4.9,
    totalSessions: 1089,
    lastUsed: "2024-01-15T11:10:00Z",
    createdAt: "2023-05-22T15:45:00Z",
    description: "Enterprise-grade scheduling with advanced timezone and resource management",
    features: ["Multi-timezone support", "Resource booking", "Recurring meetings", "Integration APIs"],
  },
]
