import type { Meeting } from "@/types/meeting"

export const meetingsData: Meeting[] = [
  {
    id: "meeting-001",
    title: "Weekly Team Standup",
    description: "Weekly sync-up to discuss progress, blockers, and upcoming tasks",
    status: "scheduled",
    type: "team",
    startTime: "2024-01-16T09:00:00Z",
    endTime: "2024-01-16T09:30:00Z",
    duration: 30,
    participants: [
      { id: "user-1", name: "John Doe", email: "john@company.com", role: "host", status: "accepted" },
      { id: "user-2", name: "Sarah Wilson", email: "sarah@company.com", role: "participant", status: "accepted" },
      { id: "user-3", name: "Mike Johnson", email: "mike@company.com", role: "participant", status: "pending" },
      { id: "user-4", name: "Emily Davis", email: "emily@company.com", role: "participant", status: "accepted" },
    ],
    host: "John Doe",
    meetingRoom: "Conference Room A",
    recordingEnabled: true,
    aiAgents: ["Meeting Assistant Pro", "Smart Scheduler"],
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "meeting-002",
    title: "Client Presentation - Q4 Results",
    description: "Quarterly business review presentation for Acme Corp",
    status: "completed",
    type: "client",
    startTime: "2024-01-15T14:00:00Z",
    endTime: "2024-01-15T15:30:00Z",
    duration: 90,
    participants: [
      {
        id: "user-1",
        name: "John Doe",
        email: "john@company.com",
        role: "host",
        status: "accepted",
        joinedAt: "2024-01-15T13:58:00Z",
        leftAt: "2024-01-15T15:32:00Z",
      },
      {
        id: "user-5",
        name: "Robert Chen",
        email: "robert@acme.com",
        role: "participant",
        status: "accepted",
        joinedAt: "2024-01-15T14:02:00Z",
        leftAt: "2024-01-15T15:30:00Z",
      },
      {
        id: "user-6",
        name: "Lisa Anderson",
        email: "lisa@acme.com",
        role: "participant",
        status: "accepted",
        joinedAt: "2024-01-15T14:00:00Z",
        leftAt: "2024-01-15T15:30:00Z",
      },
    ],
    host: "John Doe",
    meetingRoom: "Executive Suite",
    recordingEnabled: true,
    aiAgents: ["Meeting Assistant Pro", "Language Translator", "Meeting Summarizer"],
    createdAt: "2024-01-08T12:00:00Z",
    updatedAt: "2024-01-15T15:35:00Z",
  },
  {
    id: "meeting-003",
    title: "Product Development Sync",
    description: "Bi-weekly product development team synchronization meeting",
    status: "in-progress",
    type: "team",
    startTime: "2024-01-15T16:00:00Z",
    endTime: "2024-01-15T17:00:00Z",
    duration: 60,
    participants: [
      {
        id: "user-7",
        name: "Alex Thompson",
        email: "alex@company.com",
        role: "host",
        status: "accepted",
        joinedAt: "2024-01-15T15:59:00Z",
      },
      {
        id: "user-8",
        name: "Maria Garcia",
        email: "maria@company.com",
        role: "co-host",
        status: "accepted",
        joinedAt: "2024-01-15T16:01:00Z",
      },
      {
        id: "user-9",
        name: "David Kim",
        email: "david@company.com",
        role: "participant",
        status: "accepted",
        joinedAt: "2024-01-15T16:03:00Z",
      },
      {
        id: "user-10",
        name: "Jennifer Lee",
        email: "jennifer@company.com",
        role: "participant",
        status: "accepted",
        joinedAt: "2024-01-15T16:00:00Z",
      },
    ],
    host: "Alex Thompson",
    meetingRoom: "Innovation Lab",
    recordingEnabled: false,
    aiAgents: ["Analytics Engine"],
    createdAt: "2024-01-01T10:00:00Z",
    updatedAt: "2024-01-15T16:00:00Z",
  },
  {
    id: "meeting-004",
    title: "New Employee Onboarding",
    description: "Orientation session for new team members",
    status: "scheduled",
    type: "training",
    startTime: "2024-01-17T10:00:00Z",
    endTime: "2024-01-17T12:00:00Z",
    duration: 120,
    participants: [
      { id: "user-11", name: "HR Manager", email: "hr@company.com", role: "host", status: "accepted" },
      { id: "user-12", name: "Tom Wilson", email: "tom@company.com", role: "participant", status: "pending" },
      { id: "user-13", name: "Anna Brown", email: "anna@company.com", role: "participant", status: "accepted" },
    ],
    host: "HR Manager",
    meetingRoom: "Training Room B",
    recordingEnabled: true,
    aiAgents: ["Meeting Assistant Pro", "Content Moderator"],
    createdAt: "2024-01-12T14:00:00Z",
    updatedAt: "2024-01-14T09:00:00Z",
  },
  {
    id: "meeting-005",
    title: "Monthly All-Hands",
    description: "Company-wide monthly meeting with leadership updates",
    status: "scheduled",
    type: "webinar",
    startTime: "2024-01-20T15:00:00Z",
    endTime: "2024-01-20T16:00:00Z",
    duration: 60,
    participants: [
      { id: "user-14", name: "CEO", email: "ceo@company.com", role: "host", status: "accepted" },
      { id: "user-15", name: "CTO", email: "cto@company.com", role: "co-host", status: "accepted" },
      { id: "user-16", name: "All Employees", email: "all@company.com", role: "participant", status: "pending" },
    ],
    host: "CEO",
    meetingRoom: "Main Auditorium",
    recordingEnabled: true,
    aiAgents: ["Meeting Assistant Pro", "Language Translator", "Analytics Engine"],
    createdAt: "2024-01-05T16:00:00Z",
    updatedAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "meeting-006",
    title: "1:1 with Sarah",
    description: "Monthly one-on-one check-in with team member",
    status: "completed",
    type: "one-on-one",
    startTime: "2024-01-14T11:00:00Z",
    endTime: "2024-01-14T11:30:00Z",
    duration: 30,
    participants: [
      {
        id: "user-1",
        name: "John Doe",
        email: "john@company.com",
        role: "host",
        status: "accepted",
        joinedAt: "2024-01-14T11:00:00Z",
        leftAt: "2024-01-14T11:32:00Z",
      },
      {
        id: "user-2",
        name: "Sarah Wilson",
        email: "sarah@company.com",
        role: "participant",
        status: "accepted",
        joinedAt: "2024-01-14T11:01:00Z",
        leftAt: "2024-01-14T11:30:00Z",
      },
    ],
    host: "John Doe",
    meetingRoom: "Private Office",
    recordingEnabled: false,
    aiAgents: [],
    createdAt: "2024-01-07T09:00:00Z",
    updatedAt: "2024-01-14T11:35:00Z",
  },
  {
    id: "meeting-007",
    title: "Security Review Meeting",
    description: "Monthly security and compliance review session",
    status: "cancelled",
    type: "team",
    startTime: "2024-01-18T13:00:00Z",
    endTime: "2024-01-18T14:00:00Z",
    duration: 60,
    participants: [
      { id: "user-17", name: "Security Lead", email: "security@company.com", role: "host", status: "declined" },
      {
        id: "user-18",
        name: "Compliance Officer",
        email: "compliance@company.com",
        role: "participant",
        status: "declined",
      },
    ],
    host: "Security Lead",
    meetingRoom: "Secure Conference Room",
    recordingEnabled: true,
    aiAgents: ["Content Moderator"],
    createdAt: "2024-01-11T15:00:00Z",
    updatedAt: "2024-01-15T12:00:00Z",
  },
  {
    id: "meeting-008",
    title: "Design System Workshop",
    description: "Workshop on implementing the new design system across products",
    status: "scheduled",
    type: "training",
    startTime: "2024-01-19T14:00:00Z",
    endTime: "2024-01-19T16:30:00Z",
    duration: 150,
    participants: [
      { id: "user-19", name: "Design Lead", email: "design@company.com", role: "host", status: "accepted" },
      { id: "user-20", name: "Frontend Team", email: "frontend@company.com", role: "participant", status: "accepted" },
      { id: "user-21", name: "Product Team", email: "product@company.com", role: "participant", status: "pending" },
    ],
    host: "Design Lead",
    meetingRoom: "Creative Studio",
    recordingEnabled: true,
    aiAgents: ["Meeting Assistant Pro", "Meeting Summarizer"],
    createdAt: "2024-01-13T10:00:00Z",
    updatedAt: "2024-01-15T14:00:00Z",
  },
]
